<?php
$page = 'about';
$prettyphoto = 'fancy';
?>
<?php include 'inc/top.php'; ?>
	<div class="main">
		<p>In the final hours of 14th April 1912 the RMS Titanic, on her maiden voyage from Southampton to New York, collided with an iceberg and ‘the unsinkable ship’ slowly sank. It was one of the most tragic disasters of the 20th Century. 1517 men, women and children lost their lives.</p>
		<p>Based on real people aboard the most legendary ship in the world, Titanic The Musical is a stunning and stirring production focusing on the hopes, dreams and aspirations of her passengers who each boarded with stories and personal ambitions of their own. All innocently unaware of the fate awaiting them, the Third Class immigrants dream of a better life in America, the Second Class imagine they too can join the lifestyles of the rich and famous, whilst the millionaire Barons of the First Class anticipate legacies lasting forever.</p>
		<p>With music and lyrics by Maury Yeston and a book by Peter Stone (Woman of the Year and 1776), the pair have collectively won an Academy Award, an Emmy Award, an Olivier Award and three Tony awards. The original Broadway production of Titanic The Musical won five Tony Awards including Best Musical, Best Score and Best Book. This stunning production celebrates the 10th anniversary of its London premiere where it won sweeping critical acclaim across the board.</p>
		<p>Book your tickets today for this incredible experience.</p>
	</div>
	<!-- <div class="characters">
		<h2><span class="deco">--- </span>Characters<span class="deco"> ---</span></h2>
		<p style="padding-bottom:20px;">A selection of Characters from the show. Click to reveal their story.</p>

		<ul class="tags atsalt mobileonly">
			<li><a data-fancybox="gallery1" href="characters/thomas-andrews-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Thomas Andrews</span>
				<span class="role">RMS Titanic’s Architect and Managing Director of Harland & Wolff shipbuilders</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/frederick-barrett-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Frederick Barrett</span>
				<span class="role">Stoker</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/alice-beane-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Alice Beane</span>
			<span class="role">2nd Class Passenger, his wife, a social climber</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/harold-bride-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Harold Bride</span>
				<span class="role">Wireless Operator</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/frederick-fleet-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Frederick Fleet</span>
				<span class="role">Lookout </span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/bruce-ismay-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">J. Bruce Ismay</span>
				<span class="role">Chairman and Managing Director of the White Star Line, RMS Titanic’s owner</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/kate-mcgowan-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Kate McGowan</span>
				<span class="role">3rd Class Passenger, Irish</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/caroline-neville-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Lady Caroline Neville</span>
				<span class="role">2nd Class Passenger, fiancée of Charles Clark</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/edward-smith-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Captain Edward Smith</span>
				<span class="role">RMS Titanic’s Captain</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/isidor-ida-straus-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Isidor Straus</span>
				<span class="role">1st Class Passenger, owner of Macy’s</span></span></span></span></a>
			</li><li><a data-fancybox="gallery1" href="characters/isidor-ida-straus-mobile.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Ida Straus</span>
				<span class="role">1st Class Passenger, his wife</span></span></span></span></a></li>
		</ul>

		<ul class="tags atsalt notonmobile">
			<li><a data-fancybox="gallery2" href="characters/thomas-andrews.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Thomas Andrews</span>
				<span class="role">RMS Titanic’s Architect and Managing Director of Harland & Wolff shipbuilders</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/frederick-barrett.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Frederick Barrett</span>
				<span class="role">Stoker</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/alice-beane.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Alice Beane</span>
			<span class="role">2nd Class Passenger, his wife, a social climber</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/harold-bride.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Harold Bride</span>
				<span class="role">Wireless Operator</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/frederick-fleet.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Frederick Fleet</span>
				<span class="role">Lookout </span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/bruce-ismay.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">J. Bruce Ismay</span>
				<span class="role">Chairman and Managing Director of the White Star Line, RMS Titanic’s owner</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/kate-mcgowan.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Kate McGowan</span>
				<span class="role">3rd Class Passenger, Irish</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/caroline-neville.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Lady Caroline Neville</span>
				<span class="role">2nd Class Passenger, fiancée of Charles Clark</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/edward-smith.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Captain Edward Smith</span>
				<span class="role">RMS Titanic’s Captain</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/isidor-ida-straus.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Isidor Straus</span>
				<span class="role">1st Class Passenger, owner of Macy’s</span></span></span></span></a>
			</li><li><a data-fancybox="gallery2" href="characters/isidor-ida-straus.jpg"><span class="tagtop"><span class="tagbottom"><span class="tagcenter"><span class="name">Ida Straus</span>
				<span class="role">1st Class Passenger, his wife</span></span></span></span></a></li>
		</ul>
	</div> -->
	<div class="interview">
		<h2>Interview with Maury Yeston</h2>
		<p class="q">When the show was first conceived, what was it about the Titanic story you felt would lend itself well to a musical?</p>
		<p class="a">It was in the late summer/early fall of 1985 when the news hit that Robert Ballard had discovered the actual physical wreck of the Titanic on the ocean floor. That was an extraordinary moment and I began to think that, just 15 years away from the new millennium, the story of the Titanic encapsulated all the major themes of the 20<sup>th</sup> century. The ship sank in 1912, which was really culturally the beginning of the 20<sup>th</sup> century – with the likes of Debussy and Picasso and the beginning of 20<sup>th</sup> century arts. Here we were coming to the end of it and I thought it would make for an interesting theatre piece, although I didn't yet have a notion of how I would do it. I thought it was an interesting story that would capture people's imaginations. Soon afterwards, in January 1986, the US space shuttle blew up and I realised 'Good God, we haven't learned anything, have we?' With the Titanic someone forgot to put binoculars in the crow's nest and here we are in January 1986 and something called an O-ring, which is basically the seal in the rockets, lead to the deaths of seven people. It felt like we still hadn't learned not to put our unparalleled, unqualified faith in the perfection and infallibility of technology.</p>

		<p class="q">Did it feel like a brave venture at the time to tell such a dark story in a musical?</p>
		<p class="a">You'd have thought so but by 1986 musical theatre had turned a corner and was tackling subjects like Victor Hugo and French revolutionaries in Les Miserables and a murderous barber in Sondheim's Sweeney Todd. There were dark musicals that had taken tragic or unlikely ideas as their themes. I've always felt that things that sound like good ideas for musicals sometimes aren't and things that sound like very unusual ideas often are. The audience comes in going 'How can they possibly do that?' In my case, when I adapted the film 8½ into the musical Nine, I'd had 'How can they possibly make a musical out of a surreal Fellini movie?' but I knew Nine was really a story about what women mean to men and that it was something that would celebrate womanhood and teach a man how to grow up. With Titanic I knew the ending was the greatest maritime disaster in history but what the story was really about was our greatest dreams. At the end of the greatest industrial revolution in the history of the UK there was a mindset that would actually dare to think 'We might be able to build a ship that would become its own lifeboat, that it could not sink'. It's like the dream of finding a vaccine for smallpox or polio, the dream of curing cancer, of harnessing solar power and helping save the planet. Mankind has big dreams and every once in a while, despite our good intentions, the dream fails but that doesn't make us stop dreaming. I began to think that telling the tale would honour everyone who was aboard the Titanic because the ship carried everybody's dreams.</p>

		<p class="q">From researching the show, what were you interested to learn about the Titanic story?</p>
		<p class="a">That it had a rigid social structure that sank when the ship went down. Of course it was the dream of science and of the architect, of the shipbuilders in Belfast and the ship-fitters in Liverpool and the engine manufacturers in Lincoln. But it also carried the dreams of the third class passengers, who were at the cutting edge of a huge wave of migration from Europe to America seeking a better life for themselves and their children. For the second class passengers it was a dream that would not have been possible without the industrial revolution because that revolution gave the middle class enough income and leisure time to take a trip and rub elbows with the rich and famous. It's interesting to me that when you see early-19<sup>th</sup> century paintings of the beach it's always a shipwreck or a storm but late-19<sup>th</sup> century paintings show people with parasols – middle class people who could now go to a place where previously only a ship could wash up. Then you had the first class passengers, who were the wealthiest people in the world – the iron magnates, the railroad magnates, the shipbuilding magnates – and their dream was that their hegemony would last forever. When the ship went down all of those dreams crashed at the same time. It was extraordinary to think that what you wore determined whether you would live or die. The first class women all survived except for one, namely Mrs Straus who elected to stay with her husband, but so many third class passengers died. The world had to change after that.</p>

		<p class="q">110 years after the ship sank, why do you think this story continues to enthral people?</p>
		<p class="a">It's a grand story about people's bravery, cowardice and a coming together of humanity. It's also a story about how we deal with an emergency, how we deal with potential tragedy and how in the final analysis the human spirit is indomitable under the worst circumstances. In terms of the show itself, I feel as a dramatist that if you want to make an historic story into a piece of musical theatre or a play you have to a beginning, middle and end – which of course the story of the Titanic has. One of my favourite things in the theatre is when the audience knows a secret that the people on stage don't know themselves. What I found when I started developing the show with Peter Stone [who wrote the book] was that until the ship hit the iceberg the passengers were having the time of their lives. The audience comes into the theatre already knowing the ending but when you have a character kissing his girlfriend goodbye and saying 'I'll be back in a fortnight' the audience goes 'Oh my God, I know what's going to happen but he doesn't'. </p>

		<p class="q">On the first UK tour, how did it feel to launch the show in the Titanic's homeland and to play Southampton, which is where the ship originally sailed from?</p>
		<p class="a">From a personal point of view, my dad was born in Blackfriars Road in London. His family emigrated to the UK and many of my relatives still live in London. After I graduated from university in America I studied at Trent College Cambridge for two years. <br>On a personal note this tour is especially thrilling for me because I feel so connected to the United Kingdom. Then with the Titanic it's very much a British ship and a British story and when we launched the original tour in the UK, to launch the Titanic from Southampton, felt like both the show and the ship had come home – to the place where the grandfathers and great grandfathers of the audience lived and whose hands and hearts actually built the ship and who, especially in the case of Liverpool, formed so many of the staff. Then, of course, there were all the passengers from around the UK who took the journey. It's such a quintessentially British tale and no audience in the world could understand it, and take it into their hearts, as well as the British audience. It's thrilling to me to be taking it back on tour across the UK. And by the way, every character in the show has the name of someone who was actually on the Titanic. There are no invented names because we wanted to honour to those brave souls who were on the ship.</p>

		<p class="q">The musical has enjoyed a Broadway production, a US tour, a scaled-down ensemble version and a concert staging. Why do you think it lends itself to so many different interpretations?</p>
		<p class="a">I think it's a combination of the dramatic structure and the score. Once you get the show right - whether it's, say, Brigadoon or Sweeney Todd - for some extraordinary reason summer camps can do it, schools can do it, amateur operatic societies can do it, you can do it in the round, you can do it with a proscenium. I feel musicals have to work like radio plays. You should be able to hear a musical on the radio and magically see what's going on in your mind's eye. In theatre you collaborate with the imagination of the audience to create the illusion of what's on stage. Titanic works in a semi-abstract sense because of course you can't possibly put the whole ship in a theatre; you'd need 50 theatres for that. You have to imagine it and I always feel that the music should in some way reflect the mindset of the people in the story. Only the British Empire, in the late-19<sup>th</sup> and early-20<sup>th</sup> centuries, could imagine creating a ship that could never sink. In order to understand that mindset I went to the great English symphonists of the early-20<sup>th</sup> century like Elgar and Vaughan Williams. That symphonic dimension to reflect that worldview is very important in communicating to the audience the nature of the civilisation who had the daring to conceive of such an extraordinary dream.</p>

		<p class="q">Does the show have contemporary resonance?</p>
		<p class="a">I think it's more resonant than ever. We still have to learn lessons about class structure, enabling people rise above their conditions and making the opportunities in society more equal. The story of the Titanic is also inspirational because despite the tragic ending it shows that we dare and we dare nobly. When we see the examples of self-sacrifice that occur on board the ship, with some people willingly not getting into the lifeboat because they feel others should, there's inspiration in that too. There's also the theme of hoping against hope that things will somehow be OK. Even when Mr and Mrs Straus are on the deck and they know they're not going to survive they sing a song to each other which basically says 'I love you now as much as I did on the day we were married'. Even when all the women and children are off the ship and everyone left knows they're not going to survive they sing to each other 'Across the chasm we'll meet tomorrow', that somehow some of them will survive and see each other again. That's the human spirit hoping even in the face of hopelessness. </p>

		<p class="q">What do you hope audiences will take away from seeing the UK touring production?</p>
		<p class="a">I hope they will be moved, I hope they will be entertained and most importantly I hope they will be filled with the emotion of having seen the worst but also the best of what human beings can accomplish. I hope they will come away uplifted by witnessing and participating in the experience of what the human spirit can do to survive and to collaborate in helping each other.	</p>
	</div>
<?php include 'inc/bottom.php'; ?>