<?php
$name = 'Danielle Tarento';
$role = 'Producer/General Manager/Casting Director';
include '../inc/bio-top.php'; ?>

<p>Danielle is a freelance producer and casting director. She won Best Producer at the Off West End Awards 2012, was nominated Producer of the Year at the Stage Awards 2015 and was listed as one of the top ten producers of Musical Theatre in 2016 in The Stage.</p>
<p>She is co-founder of the Menier Chocolate Factory.</p>
<p>Theatre includes: <i>Vincent River, Le Grand Mort, Songs And Solidarity – A Concert For Those Affected By The Grenfell Tower Fire</i> (Trafalgar Studios); <i>Amour, Death Takes A Holiday</i> (Charing Cross Theatre); <i>Titanic</i> (UK & Ireland tour); <i>The Grift</i> (Town Hall Hotel, Bethnal Green); <i>Mother Courage And Her Children, Allegro, Gods And Monsters, Three Sisters, Victor/Victoria, Company</i> (Southwark Playhouse); <i>The Color Purple In Concert, Grateful</i> (Cadogan Hall); <i>Ragtime</i> (Charing Cross Theatre – winner, Off West End Award for Best Musical Revival 2017; nominated, WhatsOnStage Awards for Best Musical Revival and Best Off West End Production); <i>Grey Gardens</i> (Southwark Playhouse – winner, Off West End Award for Best New Musical 2017; nominated, WhatsOnStage Award for Best Off West End Production); <i>Titanic</i> (Charing Cross Theatre – winner, West End Wilma Award for Best Off West End Production 2016); <i>Pure Imagination</i> (St James Theatre); <i>Grand Hotel</i> (Southwark Playhouse – winner, Broadway World Award for Best Musical Revival 2015; nominated, WhatsOnStage Award for Best Off West End Production and 6 Off West End Awards including Best Musical Production); The Grand Tour (Finborough Theatre); <i>Man To Man</i> (Park Theatre); <i>My Lifelong Love - An Evening With Georgia Stitt And Friends</i> (Garrick Theatre); <i>Frances Ruffelle - Paris Original</i> (St James Studio); <i>Dogfight</i> (Southwark Playhouse - shortlisted, Evening Standard Theatre Award for Best Musical 2014); <i>Titanic</i> (Southwark Playhouse - longlisted, Evening Standard Theatre Award for Best Musical 2013; winner, Broadway World UK Award for Best Fringe/Regional Musical, WhatsOnStage Award for Best Off West End Production and 4 Off West End Awards including Best Musical Production); <i>Evita, Grease</i> (Ljubljana Festival, Slovenia); <i>Taboo</i> (Brixton Club House - winner, WhatsOnStage Award for Best Off West End Production 2013); <i>Mack & Mabel</i> (Southwark Playhouse - longlisted, Evening Standard Theatre Award for Best Musical 2012; nominated for 13 Broadway World UK Awards and 6 Off West End Awards); <i>The Pitchfork Disney</i> (Arcola Theatre); <i>Burlesque</i> (Jermyn Street Theatre - winner, Off West End Award for Best New Musical 2012); <i>Noël And Gertie</i> (Cockpit Theatre); <i>Parade</i> (Southwark Playhouse - longlisted, Evening Standard Theatre Award for Best Musical 2011; nominated, WhatsOnStage Award for Best Musical Revival 2012, Off West End Award for Best Musical Production); <i>Spring Awakening</i> (Rose Theatre, Kingston); <i>Drowning On Dry Land</i> (Jermyn Street Theatre); <i>Legacy Falls</i> (New Players Theatre); <i>Frances Ruffelle: Beneath The Dress</i> (Madame JoJo’s, Edinburgh Festival, Wroclaw Stage Song Review, Poland, Menier Chocolate Factory & Crazy Coqs); <i>Happy Savages</i> (Edinburgh Festival).</p>
<p>As Associate Producer: <i>Smokey Joe’s Café</i> (Landor Theatre); <i>Kurt And Sid</i> (Trafalgar Studios – nominated, WhatsOnStage Award for Best Off West End Production 2009); <i>Side By Side By Sondheim</i> (The Venue); <i>Tamburlaine The Great</i> (Rose Theatre, Bankside).</p>
<p><a href="http://www.tarento.net" target="_blank">www.tarento.net</a></p>
<?php include '../inc/bio-bottom.php'; ?>
