<?php
$name = 'Cressida Carré';
$role = 'Musical Staging';
include '../inc/bio-top.php'; ?>

<p>Theatre as Choreographer includes: <i>Violet, The Woman In White</i> (Charing Cross Theatre); <i>Turn Of The Screw</i> (Mercury Theatre, Colchester & UK tour); <i>SIX, Beyond The Fence, Seussical</i> (Arts Theatre); <i>Jersey Boys</i> (Dubai Opera House & international tour); <i>The Owl & The Pussycat</i> (Belgrade Theatre, Coventry); <i>Promises, Promises</i> (Southwark Playhouse); <i>The Star</i> (Liverpool Playhouse); <i>Sweeney Todd</i> (Derby Theatre & Mercury Theatre, Colchester) <i>Laila The Musical, Britain’s Got Bhangra, Great Expectations</i> (Watford Palace Theatre & UK tour); <i>Rumpelstiltskin</i> (MAC Belfast & The Egg, Bath); <i>20th Century Boy, Spring Awakening</i> (UK tours); <i>The Grand Tour</i> (Finborough Theatre); <i>Titanic</i> (UK & Ireland tour, Charing Cross Theatre, Princess Of Wales Theatre, Toronto & Southwark Playhouse – winner, Off West End Award for Best Choreographer); <i>Avenue Q</i> (Greenwich Theatre & UK tour); <i>The Jungle Book</i> (Glasgow Citizens); <i>Sweeney Todd, Blues Brothers</i> (Centrepoint, Dubai); <i>Spend Spend Spend</i> (Cockpit Theatre); <i>CATS</i> (Dubai); <i>Bright Lights Big City, Witches Of Eastwick</i> (Albany Theatre); <i>Songs Of My Life</i> (Garrick Theatre); <i>The Lost Christmas, Departure Lounge</i> (Waterloo East); <i>Burlesque</i> (Jermyn Street Theatre); <i>Fresher: The Musical</i> (Edinburgh Festival); <i>The Hired Man</i> (Landor Theatre); <i>As You Like It, Merlin & The Woods Of Time</i> (Grosvenor Park); <i>Cinderella</i> (Devonshire Park, Eastbourne); <i>Wind In The Willows</i> (Derby Live); <i>Elegies For Angels, Punks And Raging Queens</i> (The Black Box, Belfast); <i>Into The Woods</i> (Greenwich Theatre); <i>Jack And The Beanstalk</i> (Theatre Royal, Bury St. Edmonds); <i>Hot Mikado</i> (Chelsea Theatre); <i>Peter Pan</i> (Millfield Theatre); <i>Lucky Stiff</i> (New Wimbledon Studio).</p>
<p>Theatre as Director includes: <i>About A Bot</i> (Bridge House Theatre & Cornerstone); <i>The Wizard Of Oz</i> (Blackpool Opera House); all female <i>POSH</i> (Pleasance Theatre); <i>Spear</i> (Courtyard Theatre, Hereford); <i>The Lost Christmas</i> (Trafalgar Studios); <i>Betwixt</i> (Edinburgh Festival); <i>Marry Me A Little</i> (Etcetera Theatre).</p>
<p>Theatre as Director/Choreographer includes: <i>The Pajama Game</i> (Greenwich Theatre); <i>Eurobeat: Moldova</i> (Edinburgh Festival 2016); <i>Avenue Q</i> (Greenwich Theatre & UK tours).</p>

<?php include '../inc/bio-bottom.php'; ?>
