<?php
$name = 'Maury Yeston';
$role = 'Music & Lyrics';
include '../inc/bio-top.php'; ?>

<p>Maury Yeston is a multi award winning theatre and film composer, lyricist, author and teacher. In addition to winning a Tony Award for Best Score for <em>Titanic </em>(which won another four Tonys including Best Musical), Yeston won a Tony Award and two Drama Desk Awards for his music and lyrics to <em>Nine </em>(based on Fellini&rsquo;s1963 movie <em>8 ½</em>). That production also won four additional Tonys including Best Musical. The Broadway revival of Nine, starring Antonio Banderas, won the Tony Award for Best Musical Revival.&nbsp; Yeston&rsquo;s contribution to the score for <em>Grand Hotel</em> was nominated for a Tony and two Drama Desk Awards, and the Donmar Warehouse production won an Olivier Award.&nbsp; His score for <em>Phantom</em> has received national and international acclaim. Most recently, he wrote music and lyrics to <em>Death Takes A Holiday</em> (with a book also by Stone and Thomas Meehan), which was nominated for 11 Drama Desk Awards, and the first entirely American full length ballet,<em>Tom Sawyer: A Ballet In Three Acts </em>which premiered in Kansas City.</p>
<p>Yeston's latest project&nbsp;is entitled&nbsp;<em>The Lady Eve</em>, a new musical with book by Thomas Meehan, adapted from the legendary Preston Sturges' hilarious screwball romantic comedy film that featured Barbara Stanwyck and Henry Fonda. In addition, a revue showcasing his work, conceived and directed by Gerard Alessandrini - <em>Anything Can Happen In The Theater, The Songs of Maury Yeston</em> - opened to great acclaim at the Triad Theater in New York in the autumn of 2017.</p>
<p>In 2009, Nine was adapted into a film with a screenplay by Anthony Minghella and Michael Tolkin, directed by Rob Marshall and featuring Daniel Day-Lewis, Penelope Cruz, Marion Cotillard, Nicole Kidman, Dame Judi Dench, Kate Hudson, Fergie, and Sophia Loren. It was nominated for five Golden Globes and four Academy Awards. Yeston was nominated for a Critics Choice and Golden Globe for Best Original Song, <em>Cinema Italiano</em>, and an Academy Award for Best Original Song, <em>Take It All.</em></p>
<p>Other work includes: <em>Cello Concerto</em>, premiered by Yo Yo Ma; the concert album <em>Goya - A Life In Song</em>, featuring Placido Domingo and Gloria Estefan (the song <em>Till I Loved You</em> from the album became a Top 40 hit for Barbra Streisand); <em>December Songs</em>, a song cycle commissioned by Carnegie Hall for its centennial celebration; <em>An American Cantata - 2000 Voices</em>, a choral symphony in three movements for the National Symphony Orchestra and 2000 singers commissioned by the Kennedy Center for the Performing Arts.</p>
<p>Yeston has been twice nominated for a Grammy Award, is a lifetime member of the council of the Dramatists Guild, is on the board of the Songwriters Hall of Fame, The Kleban Foundation and The Kurt Weill Foundation. In 1998, he received The Elaine Kaufman Cultural Center Creative Arts Award in New York as Artist of The Year and was The Encompass Opera&rsquo;s Lifetime Achievement Honoree in 2009.&nbsp; In 2012 he received the distinction of being named an Honorary Ambassador of The Society of Composers &amp; Lyricists.
</p>
<?php include '../inc/bio-bottom.php'; ?>